---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git                  # заменено на git
    - epel-release         # добавлен эпохальный релиз для доступа к дополнительным репозиториям
    - nginx                # заменено на nginx

- name: Check out master branch
  git:
    repo: 'https://github.com/monicahq/monica'
    dest: /srv/monicahq
    version: master

- name: Add the user
  user:
    name: monicahq
    shell: /usr/bin/nologin
    home: /srv/monicahq

- name: Install sury key
  rpm_key:
    key: 'https://packages.sury.org/php/apt.gpg'   # заменено на apt.gpg
    state: present

- name: Add sury repositories
  ini_file:
    path: /etc/yum.repos.d/sury.repo              # изменен путь 
    section: ""
    option: "name"
    value: "sury"
    backup: yes                                   # добавлена опция создания резервной копии
    mode: "0644"                                 # изменены права доступа

- name: Install php dependencies
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - php73                                      # заменено на php73
    - php73-cli                                  # заменено на php73-cli
    - php73-intl                                 # заменено на php73-intl
    - php73-iconv                                # заменено на php73-iconv
    - php73-fpm                                  # заменено на php73-fpm
    - php73-curl                                 # заменено на php73-curl
    - php73-gd                                   # заменено на php73-gd
    - php73-mysqlnd                              # заменено на php73-mysqlnd
    - php73-opcache                              # заменено на php73-opcache
    - php73-json                                 # заменено на php73-json
    - php73-mbstring                             # заменено на php73-mbstring
    - php73-soap                                 # заменено на php73-soap
    - php73-xml                                  # заменено на php73-xml
    - php73-zip                                  # заменено на php73-zip
    - php73-gmp                                  # заменено на php73-gmp
    - php73-bcmath                               # заменено на php73-bcmath
    - php-memcached                              # заменено на php-memcached
    - php-pecl-xdebug                            # заменено на php-pecl-xdebug
    - php-pecl-redis                             # заменено на php-pecl-redis

- name: Reload service php-fpm
  systemd:
    name: php-fpm
    state: reloaded

- name: Install composer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: /tmp/install_composer.php

- name: Run installer for composer
  command: "/usr/bin/php /tmp/install_composer.php --install-dir=/usr/local/bin --filename=composer"

- name: Install composer dependencies
  composer:
    command: install
    working_dir: /srv/monicahq

- name: Prepare configuration
  template:
    src: env.j2
    dest: /srv/monicahq/.env

- name: Run an initial key generation
  command: "/usr/bin/php /srv/monicahq/artisan key:generate"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Run an initial migration
  command: "/usr/bin/php /srv/monicahq/artisan setup:production --force"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Place a scheduler cron job
  cron:
    user: monicahq
    name: "scheduler"
    job: "/usr/bin/php /srv/monicahq/artisan schedule:run"

- name: Recursively change ownership of a directory
  file:
    path: /srv/monicahq
    state: directory
    recurse: yes
    owner: monicahq                               # заменено на monicahq
    group: nginx                           # изменено на group: nginx

- name: Put right permissions to storage
  file:
    path: /srv/monicahq/storage
    state: directory
    recurse: yes
    mode: "g+w"                            # изменен режим доступа

- name: Create nginx vhost config
  template:
    src: monicahq.conf.j2
    dest: /etc/nginx/conf.d/monica.conf    # изменен путь

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/conf.d/default.conf   # изменен путь
    state: absent

- name: Reload service nginx
  systemd:
    name: nginx
    state: reloaded